template: testify
packages:
  github.com/stray4x/ecom-crm/internal/repository:
    interfaces:
      CustomerRepository:
        config:
          dir: "internal/repository/mocks"
          pkgname: mocks
          filename: "customer_repository.go"
  github.com/stray4x/ecom-crm/internal/service:
    interfaces:
      AuthService:
        config:
          dir: "internal/service/mocks"
          pkgname: mocks
          filename: "auth_service.go"
  github.com/stray4x/ecom-crm/internal/redis:
    interfaces:
      TokenStore:
        config:
          dir: "internal/redis/mocks"
          pkgname: mocks
          filename: "token_store.go"