// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/google/uuid"
	"github.com/stray4x/ecom-crm/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomerRepository creates a new instance of MockCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerRepository {
	mock := &MockCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerRepository is an autogenerated mock type for the CustomerRepository type
type MockCustomerRepository struct {
	mock.Mock
}

type MockCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerRepository) EXPECT() *MockCustomerRepository_Expecter {
	return &MockCustomerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) Create(customer *models.Customer) error {
	ret := _mock.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Customer) error); ok {
		r0 = returnFunc(customer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCustomerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - customer *models.Customer
func (_e *MockCustomerRepository_Expecter) Create(customer any) *MockCustomerRepository_Create_Call {
	return &MockCustomerRepository_Create_Call{Call: _e.mock.On("Create", customer)}
}

func (_c *MockCustomerRepository_Create_Call) Run(run func(customer *models.Customer)) *MockCustomerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Customer
		if args[0] != nil {
			arg0 = args[0].(*models.Customer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_Create_Call) Return(err error) *MockCustomerRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerRepository_Create_Call) RunAndReturn(run func(customer *models.Customer) error) *MockCustomerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) GetByEmail(email string) (*models.Customer, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.Customer, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.Customer); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockCustomerRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockCustomerRepository_Expecter) GetByEmail(email any) *MockCustomerRepository_GetByEmail_Call {
	return &MockCustomerRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", email)}
}

func (_c *MockCustomerRepository_GetByEmail_Call) Run(run func(email string)) *MockCustomerRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_GetByEmail_Call) Return(customer *models.Customer, err error) *MockCustomerRepository_GetByEmail_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerRepository_GetByEmail_Call) RunAndReturn(run func(email string) (*models.Customer, error)) *MockCustomerRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) GetByID(id uuid.UUID) (*models.Customer, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*models.Customer, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *models.Customer); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCustomerRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockCustomerRepository_Expecter) GetByID(id any) *MockCustomerRepository_GetByID_Call {
	return &MockCustomerRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockCustomerRepository_GetByID_Call) Run(run func(id uuid.UUID)) *MockCustomerRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_GetByID_Call) Return(customer *models.Customer, err error) *MockCustomerRepository_GetByID_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerRepository_GetByID_Call) RunAndReturn(run func(id uuid.UUID) (*models.Customer, error)) *MockCustomerRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) Update(customer *models.Customer) error {
	ret := _mock.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Customer) error); ok {
		r0 = returnFunc(customer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCustomerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - customer *models.Customer
func (_e *MockCustomerRepository_Expecter) Update(customer any) *MockCustomerRepository_Update_Call {
	return &MockCustomerRepository_Update_Call{Call: _e.mock.On("Update", customer)}
}

func (_c *MockCustomerRepository_Update_Call) Run(run func(customer *models.Customer)) *MockCustomerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Customer
		if args[0] != nil {
			arg0 = args[0].(*models.Customer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_Update_Call) Return(err error) *MockCustomerRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerRepository_Update_Call) RunAndReturn(run func(customer *models.Customer) error) *MockCustomerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
