// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenStore creates a new instance of MockTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenStore {
	mock := &MockTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenStore is an autogenerated mock type for the TokenStore type
type MockTokenStore struct {
	mock.Mock
}

type MockTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenStore) EXPECT() *MockTokenStore_Expecter {
	return &MockTokenStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) Delete(ctx context.Context, customerID string, sessionID string) error {
	ret := _mock.Called(ctx, customerID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, customerID, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTokenStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
//   - sessionID string
func (_e *MockTokenStore_Expecter) Delete(ctx any, customerID any, sessionID any) *MockTokenStore_Delete_Call {
	return &MockTokenStore_Delete_Call{Call: _e.mock.On("Delete", ctx, customerID, sessionID)}
}

func (_c *MockTokenStore_Delete_Call) Run(run func(ctx context.Context, customerID string, sessionID string)) *MockTokenStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenStore_Delete_Call) Return(err error) *MockTokenStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenStore_Delete_Call) RunAndReturn(run func(ctx context.Context, customerID string, sessionID string) error) *MockTokenStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) Get(ctx context.Context, customerID string, sessionID string) (string, error) {
	ret := _mock.Called(ctx, customerID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, customerID, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, customerID, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, customerID, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTokenStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
//   - sessionID string
func (_e *MockTokenStore_Expecter) Get(ctx any, customerID any, sessionID any) *MockTokenStore_Get_Call {
	return &MockTokenStore_Get_Call{Call: _e.mock.On("Get", ctx, customerID, sessionID)}
}

func (_c *MockTokenStore_Get_Call) Run(run func(ctx context.Context, customerID string, sessionID string)) *MockTokenStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenStore_Get_Call) Return(s string, err error) *MockTokenStore_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenStore_Get_Call) RunAndReturn(run func(ctx context.Context, customerID string, sessionID string) (string, error)) *MockTokenStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) Save(ctx context.Context, customerID string, sessionID string, token string, ttl time.Duration) error {
	ret := _mock.Called(ctx, customerID, sessionID, token, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, customerID, sessionID, token, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTokenStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
//   - sessionID string
//   - token string
//   - ttl time.Duration
func (_e *MockTokenStore_Expecter) Save(ctx any, customerID any, sessionID any, token any, ttl any) *MockTokenStore_Save_Call {
	return &MockTokenStore_Save_Call{Call: _e.mock.On("Save", ctx, customerID, sessionID, token, ttl)}
}

func (_c *MockTokenStore_Save_Call) Run(run func(ctx context.Context, customerID string, sessionID string, token string, ttl time.Duration)) *MockTokenStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTokenStore_Save_Call) Return(err error) *MockTokenStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenStore_Save_Call) RunAndReturn(run func(ctx context.Context, customerID string, sessionID string, token string, ttl time.Duration) error) *MockTokenStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
