// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/stray4x/ecom-crm/internal/dto"
	"github.com/stray4x/ecom-crm/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(req dto.LoginRequest) (*dto.CustomerResponse, *service.Tokens, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.CustomerResponse
	var r1 *service.Tokens
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(dto.LoginRequest) (*dto.CustomerResponse, *service.Tokens, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(dto.LoginRequest) *dto.CustomerResponse); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(dto.LoginRequest) *service.Tokens); ok {
		r1 = returnFunc(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*service.Tokens)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(dto.LoginRequest) error); ok {
		r2 = returnFunc(req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - req dto.LoginRequest
func (_e *MockAuthService_Expecter) Login(req any) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", req)}
}

func (_c *MockAuthService_Login_Call) Run(run func(req dto.LoginRequest)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.LoginRequest
		if args[0] != nil {
			arg0 = args[0].(dto.LoginRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(customerResponse *dto.CustomerResponse, tokens *service.Tokens, err error) *MockAuthService_Login_Call {
	_c.Call.Return(customerResponse, tokens, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(req dto.LoginRequest) (*dto.CustomerResponse, *service.Tokens, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Refresh(refreshToken string) (*service.Tokens, error) {
	ret := _mock.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *service.Tokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*service.Tokens, error)); ok {
		return returnFunc(refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *service.Tokens); ok {
		r0 = returnFunc(refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Tokens)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - refreshToken string
func (_e *MockAuthService_Expecter) Refresh(refreshToken any) *MockAuthService_Refresh_Call {
	return &MockAuthService_Refresh_Call{Call: _e.mock.On("Refresh", refreshToken)}
}

func (_c *MockAuthService_Refresh_Call) Run(run func(refreshToken string)) *MockAuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_Refresh_Call) Return(tokens *service.Tokens, err error) *MockAuthService_Refresh_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *MockAuthService_Refresh_Call) RunAndReturn(run func(refreshToken string) (*service.Tokens, error)) *MockAuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(req dto.RegisterCustomerRequest) (*dto.CustomerResponse, *service.Tokens, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *dto.CustomerResponse
	var r1 *service.Tokens
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(dto.RegisterCustomerRequest) (*dto.CustomerResponse, *service.Tokens, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(dto.RegisterCustomerRequest) *dto.CustomerResponse); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(dto.RegisterCustomerRequest) *service.Tokens); ok {
		r1 = returnFunc(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*service.Tokens)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(dto.RegisterCustomerRequest) error); ok {
		r2 = returnFunc(req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - req dto.RegisterCustomerRequest
func (_e *MockAuthService_Expecter) Register(req any) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", req)}
}

func (_c *MockAuthService_Register_Call) Run(run func(req dto.RegisterCustomerRequest)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.RegisterCustomerRequest
		if args[0] != nil {
			arg0 = args[0].(dto.RegisterCustomerRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(customerResponse *dto.CustomerResponse, tokens *service.Tokens, err error) *MockAuthService_Register_Call {
	_c.Call.Return(customerResponse, tokens, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(req dto.RegisterCustomerRequest) (*dto.CustomerResponse, *service.Tokens, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}
